def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any 

    environment {
        cluster = "prod-cluster"
        service = "prod-svc"
    }

    stages {
        
        stage ("Deploy_To_Prod_ECS") {
            steps {
                withAWS(credentials: "aws_creds", region: "ap-south-1") {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }

    post {
        always {
            echo 'slack notification'
            slackSend channel: '#jenkins-ci_cd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n more info at: ${env.BUILD_URL}"
                echo "YOUR IMAGE SUCCESSFULLY DEPLOYED TO PRODUCTION ENVIRONMENT........"
        }
    }
}
